<html>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <title>Bootstrap Task-1</title>
    <style>
        *{
            overflow: hidden;
        }
    </style>
</head>

<body>
    <nav>
        <div class="text-center bg-info">
            <h2>Ethnus layout</h2>
            <div class="navbar bg-secondary">
                <div class="nav">
                    <a class="nav-link text-light mx-4" href="#">HOME</a>
                    <a class="nav-link text-light mx-4" href="#">MENU</a>
                    <a class="nav-link text-light mx-4" href="#">ABOUT</a>
                    <a class="nav-link text-light mx-4" href="#">CONTACT</a>
                </div>
                <div class="nav">
                    <a class="nav-link text-light mx-4" href="#">SIGNUP</a>
                    <a class="nav-link text-light mx-4" href="#">LOGIN</a>
                </div>
            </div>
        </div>
    </nav>

    <main>
        <div class="row">
            <div class="col-10 text-center">
                <p>Write your content here</p>
            </div>
            <div class="col-2 bg-dark text-center" style="height: 1000px;">
                <span class="text-light">This is</span>
            </div>
        </div>
    </main>
</body>

</html>