<html>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <title>Bootstrap Task-2</title>
    <style>
        .btn-custom{
            border: 2px solid white;
            color: white;
            border-radius: 0;
        }
        span{
            font-size: 14px;
        }
        .bg-image{
            background-image: url(photo.png);
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        .btn-custom:hover{
            border: 2px solid rgb(203, 203, 203);
            color: rgb(203, 203, 203);
        }
    </style>
</head>

<body class="bg-warning">
    <div class="row mx-4">
        <h1 class="col-4 fw-bolder display-4 px-5">Builderz</h1>
        <table class="col-3">
            <tr>
                <td class="text-end"><i class="fa-regular fa-calendar fs-1"></i></td>
                <td class="ps-3">Opening Hour <br><span>Mon-Fri 8:00 - 9:00</span></td>
            </tr>
        </table>
        <table class="col-3">
            <tr>
                <td class="text-end"><i class="fa-solid fa-tty fs-1"></i></td>
                <td class="ps-3">Call us <br><span>+012 345 6789</span></td>
            </tr>
        </table>
        <table class="col-2">
            <tr>
                <td class="text-end"><i class="fa-regular fa-envelope fs-1"></i></td>
                <td class="ps-3">Email us <br><span>info@example.com</span></td>
            </tr>
        </table>
        <div class="col-12 px-5">
            <div class="navbar bg-dark">
                <div class="nav m-3">
                    <a href="#" class="nav-link text-light">HOME</a>
                    <a href="#" class="nav-link text-light">ABOUT</a>
                    <a href="#" class="nav-link text-light">SERVICE</a>
                    <a href="#" class="nav-link text-light">TEAM</a>
                    <a href="#" class="nav-link text-light">PROJECT</a>
                    <a href="#" class="nav-link dropdown-toggle text-light">PAGES</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item-text" href="#">Page-1</a></li>
                        <li><a class="dropdown-item-text" href="#">Page-2</a></li>
                        <li><a class="dropdown-item-text" href="#">Page-3</a></li>
                    </ul>
                </div>
                <div class="nav">
                    <button class="btn btn-custom me-4">Get A Quote</button>
                </div>
            </div>
        </div>
    </div>
    <div class="bg-image m-0 p-0 text-center text-light">
        <h6 class="fs-2" style="padding-top: 15%;">We are Professional</h6> <br>
        <h1 class="fw-bolder display-3">For Your Dream Project</h1> <br><br>
        <button class="btn btn-custom px-5 py-3"> GET A QUOTE</button>
    </div>
    
    <div class="row me-0">
        <div class="col-4 text-center bg-dark p-5">
            <table style="width: 100%;">
                <tr class="text-warning">
                    <td class="p-4 text-end"><i class="fa-solid fa-helmet-safety h1 display-2"></i></td>
                    <td> 
                        <h4>Expert Worker</h4>
                        Lorem ipsum dolor sit amet <br>elit. Phasus nec pretim ornare <br>velit non
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-4 text-center p-5">
            <table style="width: 100%;">
                <tr class="text-dark">
                    <td class="p-4 text-end"><i class="fa-solid fa-city h1 display-2"></i></td>
                    <td> 
                        <h4>Quality Work</h4>
                        Lorem ipsum dolor sit amet <br>elit. Phasus nec pretim ornare <br>velit non
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-4 text-center bg-dark p-5">
            <table style="width: 100%;">
                <tr class="text-warning">
                    <td class="p-4 text-end"><i class="fa-solid fa-headset h1 display-2"></i></td>
                    <td> 
                        <h4>24/7 Support</h4>
                        Lorem ipsum dolor sit amet <br>elit. Phasus nec pretim ornare <br>velit non
                    </td>
                </tr>
            </table>
        </div>
    </div>
</body>

</html>