<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <title>Bootstrap Task-3</title>
        <style>
            .btn-custom{
                border: 2px solid rgb(13, 110, 253);
                color: rgb(13, 110, 253);
            }
            .btn-custom:hover{
                border: 2px solid rgb(0, 0, 141);
                color: rgb(0, 0, 141);
            }
        </style>
    </head>
    <body>
        <nav>
            <div class="navbar mx-4">
                <div class="navbar-brand">
                    Company name
                </div>
                <div class="nav">
                    <a class="nav-link text-dark" href="#">Features</a>
                    <a class="nav-link text-dark" href="#">Enterprise</a>
                    <a class="nav-link text-dark" href="#">Support</a>
                    <a class="nav-link text-dark" href="#">Pricing</a>
                    <button class="btn btn-custom mx-2">Sign up</button>
                </div>
            </div>
            <hr class="m-1" style="box-shadow: 0px 1px 3px 1px; border: 0;">
        </nav>
        <main>
            <div class="container mt-5">
                <p class="display-1 text-center">Pricing</p>
                <p class="text-center">
                    Quickly build an effective pricing table for your potential customer with this <br>
                    Bootstrap example. It's built with default Bootstrap components and utilities <br>
                    with little customization. 
                </p>
                <br>
                <div class="row" style="margin-right: 10%; margin-left: 10%;">
                    <div class="col-4">
                        <div class="card text-center">
                            <div class="card-header p-3">
                                Free
                            </div>
                            <div class="card-title p-3">
                                <h1>$0 <span style="color: lightgray; font-size: xx-large;"> / mo </span></h1>
                            </div>
                            <div class="card-text pb-3">
                                10 users included <br>
                                2 GB of storage <br>
                                Email support <br>
                                Help center access
                            </div>
                            <div class="card-text">
                                <button class="btn btn-custom mb-3" style= "width:90%;">Sign up for free</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="card text-center">
                            <div class="card-header p-3">
                                Free
                            </div>
                            <div class="card-title p-3">
                                <h1>$15 <span style="color: lightgray; font-size: xx-large;"> / mo </span></h1>
                            </div>
                            <div class="card-text pb-3">
                                20 users included <br>
                                10 GB of storage <br>
                                Priority email support <br>
                                Help center access
                            </div>
                            <div class="card-text">
                                <button class="btn btn-primary mb-3" style= "width:90%;">Get Started</button>
                            </div>
                        </div>
                    </div>


                    <div class="col-4">
                        <div class="card text-center">
                            <div class="card-header p-3">
                                Free
                            </div>
                            <div class="card-title p-3">
                                <h1>$29 <span style="color: lightgray; font-size: xx-large;"> / mo </span></h1>
                            </div>
                            <div class="card-text pb-3">
                                30 users included <br>
                                15 GB of storage <br>
                                Phone and email support <br>
                                Help center access
                            </div>
                            <div class="card-text">
                                <button class="btn btn-primary mb-3" style= "width:90%;">Contact us</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer>
            <div class="row mt-5" style="margin-right: 15%; margin-left: 15%;">
                <hr><br><br>    
                <div class="col-3">
                    <img src="photo_2.png" style="width: 40px;"><br>
                    &nbsp;&#169;2017 
                </div>
                <div class="col-3">
                    <p>
                        <span style="font-weight: bold; font-size: 20px;">Features</span><br><br>
                        Cool Stuff <br>
                        Random features <br>
                        Team features
                    </p>
                </div>
                <div class="col-3">
                    <p>
                        <span style="font-weight: bold; font-size: 20px;">Resources</span><br><br>
                        Resource <br>
                        Resource name <br>
                        Another resource
                    </p>
                </div>
                <div class="col-3">
                    <p>
                        <span style="font-weight: bold; font-size: 20px;">About</span><br><br>
                        Team <br>
                        Location <br>
                        Privacy
                    </p>
                </div>
            </div>
        </footer>
    </body>
</html>