<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <title>Bootstrap Task-6</title>
        <style>
            body{
                margin-left: 30%;
                margin-right: 30%;
                margin-top: 30px;
            }
            #x{
                height: 40px;
                padding: 10px;
                border: 1px solid;
                border-radius: 6px;
               
            }
        </style>
    </head>
    <body>
        <div>
            <form action="#" class="was-validated">
                <label for="firstname" class="form-label">Name</label>
                <div class="input-group has-validation">    
                    <input type="text" name="firstname" class="form-control" id="input" required>
                    <div class="invalid-feedback">
                        Name is required
                    </div>
                </div>
                <br>
                <label for="email" class="form-label">Email</label>
                <div class="input-group has-validation">    
                    <input type="email" name="email" class="form-control" required>
                    <div class="invalid-feedback">
                        Email is required
                    </div>
                </div>
                <br>
                <label for="password" class="form-label">Password</label>
                <div class="input-group has-validation">    
                    <input type="password" name="password" class="form-control" required>
                    <div class="invalid-feedback">
                        Password is required
                    </div>
                </div>
                <br>
                <label for="hobbies" class="form-label">Hobbies</label>
                <div class="input-group">
                    <input type="number" name="hobbies" class="w-100" id="x" required>
                </div>
                <br>
                <button type="submit" class="btn btn-danger w-100">Submit</button>  
            </form>
        </div>
    </body>
</html>