<html>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <title>Bootstrap Task-4</title>
    <style>
        a{
            color: rgb(232, 197, 0);
            text-decoration: none;
        }
        img{
            border-top-right-radius: 5px;
            border-top-left-radius: 5px;
        }
        .row{
            justify-content: center;
            align-items: center;
            display: flex;
        }
        span.card-title{
           font-size: 24px;
        }
    </style>
</head>

<body>
    <hr style="border: 1px solid black;">
    <div class="container">
        <div class="row m-4">
            <div class="col-2">
                <div class="card" style="width: 190px; height: 600px;">
                    <img src="photo_3.png" class="card-img">
                    <div class="card-img-overlay"><br><br><br><br>
                        <span class="card-title text-white "></span>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item my-3">Cards for display in portfoloi style material designed by Google.</li>
                    </ul>
                    <div class="card-body my-1">
                        <a href="#" class="card-link">LINK</a>
                        <a href="#" class="card-link">LINK</a>
                    </div>
                </div>
            </div>
            <div class="col-2"> 
                <div class="card" style="width: 190px; height: 600px;">
                    <img src="photo_4.png">
                    <div class="card-img-overlay pt-1"><br><br>
                        <span class="card-title text-white "></span>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item my-3">Cards for display in portfoloi style material designed by Google.</li>
                    </ul>
                    <div class="card-body my-1">
                        <a href="#" class="card-link">LINK</a>
                        <a href="#" class="card-link">LINK</a>
                    </div>
                </div>
            </div>
            <div class="col-2"> 
                <div class="card" style="width: 190px; height: 600px;">
                    <img src="photo_4.png">
                    <div class="card-img-overlay pt-1"><br><br>
                        <span class="card-title text-white "></span>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item my-3">Cards for display in portfoloi style material designed by Google.</li>
                    </ul>
                    <div class="card-body my-1">
                        <a href="#" class="card-link">LINK</a>
                        <a href="#" class="card-link">LINK</a>
                    </div>
                </div>
            </div>
            <div class="col-2"> 
                <div class="card" style="width: 190px; height: 600px;">
                    <img src="photo_4.png">
                    <div class="card-img-overlay pt-1"><br><br>
                        <span class="card-title text-white "></span>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item my-3">Cards for display in portfoloi style material designed by Google.</li>
                    </ul>
                    <div class="card-body my-1">
                        <a href="#" class="card-link">LINK</a>
                        <a href="#" class="card-link">LINK</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>